# Generated by Django 5.0.6 on 2024-05-21 18:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_expenseinfo_delete_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(choices=[('Spożywcze', 'Spożywcze'), ('Chemia', 'Chemia'), ('Rachunki', 'Rachunki'), ('Alkohol', 'Alkohol'), ('Gry', 'Gry')], default='Spożywcze')),
                ('cost', models.FloatField(default=0, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_expense', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('income', models.FloatField(default=0, null=True)),
                ('user_income', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ExpenseInfo',
        ),
    ]
