# Generated by Django 5.0.6 on 2024-05-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_userdata_incomedata_category_incomedata_cost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
        migrations.AlterField(
            model_name='incomedata',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
