# Generated by Django 5.0.6 on 2024-05-22 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_userdata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
        migrations.RemoveField(
            model_name='incomedata',
            name='category',
        ),
        migrations.RemoveField(
            model_name='incomedata',
            name='cost',
        ),
        migrations.AlterField(
            model_name='budgetdata',
            name='category',
            field=models.CharField(choices=[('Spożywcze', 'Spożywcze'), ('Chemia', 'Chemia'), ('Rachunki', 'Rachunki'), ('Alkohol', 'Alkohol'), ('Gry', 'Gry')], default='Spożywcze', max_length=100),
        ),
        migrations.AlterField(
            model_name='budgetdata',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='budgetdata',
            name='user_expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incomedata',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='incomedata',
            name='user_income',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
