# Generated by Django 5.0.6 on 2024-05-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_delete_userdata_remove_incomedata_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetdata',
            name='category',
            field=models.CharField(choices=[('Nourriture', 'Nourriture'), ('Hygiène', 'Hygiène'), ('Factures', 'Factures'), ('Alcool', 'Alcool'), ('Jeux', 'Jeux')], default='Nourriture', max_length=100),
        ),
    ]
