# Generated by Django 5.0.6 on 2024-05-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_alter_budgetdata_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetdata',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
